name: oblt-google-auth
description: Grant pipelines access to Google Cloud resources using Workload Identity Federation
author: https://github.com/elastic
public: true
requirements:
  - bash
  - buildkite-agent
configuration:
  properties:
    lifetime:
      type: number
    project-id:
      type: string
    project-number:
      type: number
    use-service-account:
      type: boolean
    slack-channel:
      type: string
  additionalProperties: false
