env:
  GOOGLE_PROJECT: "elastic-observability-ci"

steps:
  - label: ":gcp: Google Cloud Auth OIDC Test"
    agents:
      provider: gcp
    plugins:
      - elastic/oblt-google-auth#${BUILDKITE_COMMIT}:
        lifetime: 10800 # seconds
        project-id: "elastic-observability-ci"
        project-number: "911195782929"
    command: |
      #!/usr/bin/env bash
      set +eu

      echo "Listing service account"
      gcloud iam service-accounts list --project=${GOOGLE_PROJECT}

  - label: ":gcp: Google Cloud Auth Service Account Test"
    agents:
      provider: gcp
    plugins:
      - elastic/oblt-google-auth#${BUILDKITE_COMMIT}:
        lifetime: 10800 # seconds
        project-id: "elastic-observability-ci"
        project-number: "911195782929"
        use-service-account: true
    command: |
      #!/usr/bin/env bash
      set +eu

      echo "Listing service accounts"
      gcloud iam service-accounts list --project=${GOOGLE_PROJECT}
