env:
  GOOGLE_PROJECT: "elastic-observability-ci"
common:
  - google_oidc_plugin: &google_oidc_plugin
    # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/elastic-agent/01-gcp-oidc.tf
    # This plugin authenticates to Google Cloud using the OIDC token.
    elastic/oblt-google-auth#${BUILDKITE_COMMIT}:
      lifetime: 10800 # seconds
      project-id: "elastic-observability-ci"
      project-number: "911195782929"

steps:
  - label: ":gcp: Google Cloud Auth OIDC Test"
    agents:
      provider: gcp
    plugins:
      - elastic/oblt-google-auth#${BUILDKITE_COMMIT}:
        lifetime: 10800 # seconds
        project-id: "elastic-observability-ci"
        project-number: "911195782929"
    command: |
      #!/usr/bin/env bash
      set +eu

      echo "Listing service account"
      gcloud iam service-accounts list --project=${GOOGLE_PROJECT}

  - label: ":gcp: Google Cloud Auth Service Account Test"
    agents:
      provider: gcp
    plugins:
      - elastic/oblt-google-auth#${BUILDKITE_COMMIT}:
        lifetime: 10800 # seconds
        project-id: "elastic-observability-ci"
        project-number: "911195782929"
        use-service-account: true
    command: |
      #!/usr/bin/env bash
      set +eu

      echo "Listing service accounts"
      gcloud iam service-accounts list --project=${GOOGLE_PROJECT}
