env:
  GOOGLE_PROJECT: "elastic-observability-ci"

steps:
  - label: ":gcp: Google Cloud Auth OIDC Test"
    agents:
      provider: gcp
      image: family/core-ubuntu-2204
    plugins:
      - elastic/oblt-google-auth#${BUILDKITE_COMMIT}:
          lifetime: 10800 # seconds
          project-id: "elastic-observability-ci"
          project-number: "911195782929"
    command: |
      #!/usr/bin/env bash
      set +eu

      echo "Listing active auth accounts"
      gcloud auth list --filter=status:ACTIVE --project=${GOOGLE_PROJECT}
