#!/usr/bin/env bash

set -euo pipefail

# Create a temporary directory with both BSD and GNU mktemp
TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'buildkiteXXXX')

CREDENTIALS_FILE="$TMPDIR"/credentials.json
TOKEN_FILE="$TMPDIR"/token.json

CWD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "~~~ :buildkite: Requesting OIDC token from Buildkite"

HASH=$(echo "${BUILDKITE_REPO}" | awk -F'[:.]' '{ printf $3 }' | sha256sum | cut -c1-27)

PROJECT_NUMBER="${BUILDKITE_PLUGIN_OBLT_GOOGLE_AUTH_PROJECT_NUMBER:-"8560181848"}"
PROJECT_ID="${BUILDKITE_PLUGIN_OBLT_GOOGLE_AUTH_PROJECT_ID:-"elastic-observability"}"
WORKLOAD_IDENTITY_POOL_ID="buildkite"
WORKLOAD_IDENTITY_PROVIDER_ID="repo-${HASH}"
AUDIENCE="//iam.googleapis.com/projects/${PROJECT_NUMBER}/locations/global/workloadIdentityPools/${WORKLOAD_IDENTITY_POOL_ID}/providers/${WORKLOAD_IDENTITY_PROVIDER_ID}"
buildkite-agent oidc request-token --audience "$AUDIENCE" --lifetime "${BUILDKITE_PLUGIN_OBLT_GOOGLE_AUTH_LIFETIME:-1800}" > "$TOKEN_FILE"
echo "Workload Identity Provider ID: ${WORKLOAD_IDENTITY_PROVIDER_ID}"

echo "~~~ :gcloud: Configuring Google Cloud credentials"

if [[ "$OSTYPE" =~ ^(win|msys|cygwin) ]] ; then
  # Convert paths to Windows format
  TOKEN_FILE="$(cygpath -w "$TOKEN_FILE")"
  # Escape backslashes for JSON by doubling them
  TOKEN_FILE="$(echo "$TOKEN_FILE" | sed 's/\\/\\\\/g')"
fi

export BUILDKITE_OIDC_TMPDIR="${TMPDIR}"
export GOOGLE_APPLICATION_CREDENTIALS="${CREDENTIALS_FILE}"
export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE="${GOOGLE_APPLICATION_CREDENTIALS}"
export CLOUDSDK_CORE_PROJECT="${PROJECT_ID}"
export CLOUDSDK_PROJECT="${PROJECT_ID}"
export GCLOUD_PROJECT="${PROJECT_ID}"
export GCP_PROJECT="${PROJECT_ID}"
export GOOGLE_CLOUD_PROJECT="${PROJECT_ID}"
