#!/usr/bin/env bash

set -euo pipefail

# Functions for Google Cloud Service Account management

LABEL_ORG="obs"
LABEL_DIVISION="engineering"
LABEL_TEAM="eng-productivity"
LABEL_PROJECT=${BUILDKITE_REPO}
LABEL_EPHEMERAL="true"

# Create the service account
# Arguments:
#   $1: Service account name
#   $2: Token file path
#   $3: Project ID
#   $4: Request file path
#   $5: Hash
function create_service_account() {
  local -r SA_NAME="$1"
  local -r TOKEN_FILE="$2"
  local -r PROJECT_ID="$3"
  local -r REQUEST_FILE="$4"
  local -r HASH="$5"
  cat << JSON > "$REQUEST_FILE"
{
  "accountId": "$SA_NAME",
  "serviceAccount": {
    "description": "Automated service account created by Buildkite GCP Auth Plugin with the hash ${HASH}.\n Labels:\n org=${LABEL_ORG}\n division=${LABEL_DIVISION}\n team=${LABEL_TEAM}\n project=${LABEL_PROJECT}\n ephemeral=${LABEL_EPHEMERAL}",
    "displayName": "Buildkite Plugin Service Account ${HASH}"
  }
}
JSON

  curl -X POST \
    -H "Authorization: Bearer $(cat $TOKEN_FILE)" \
    -H "Content-Type: application/json; charset=utf-8" \
    -d @$REQUEST_FILE \
    "https://iam.googleapis.com/v1/projects/$PROJECT_ID/serviceAccounts"
}

# Set the IAM policy to the service account
# Arguments:
#   $1: Service account email
#   $2: Token file path
#   $3: Project ID
#   $4: Request file path
function set_iam_policy() {
  local -r SA_ACCOUNT="$1"
  local -r TOKEN_FILE="$2"
  local -r PROJECT_ID="$3"
  local -r REQUEST_FILE="$4"
  cat << JSON > "$REQUEST_FILE"
{
  "policy": {
    "bindings": [
      {
        "role": "roles/writer",
        "members": [
          "$SA_ACCOUNT"
        ]
      }
    ]
  }
}
JSON

  curl -X POST \
    -H "Authorization: Bearer $(cat $TOKEN_FILE)" \
    -H "Content-Type: application/json; charset=utf-8" \
    -d @$REQUEST_FILE \
    "https://cloudresourcemanager.googleapis.com/v1/projects/$PROJECT_ID:setIamPolicy"

}

# Create and download the service account key
# Arguments:
#   $1: Service account email
#   $2: Token file path
#   $3: Project ID
#   $4: Service account key file path
function create_service_account_key() {
  local -r SA_ACCOUNT="$1"
  local -r TOKEN_FILE="$2"
  local -r PROJECT_ID="$3"
  local -r SA_KEY_FILE="$4"
  curl -X POST \
    -H "Authorization: Bearer $(cat $TOKEN_FILE)" \
    -H "Content-Type: application/json; charset=utf-8" \
    "https://iam.googleapis.com/v1/projects/$PROJECT_ID/serviceAccounts/$SA_ACCOUNT/keys" > "$SA_KEY_FILE"
}