#!/usr/bin/env bash

set -euo pipefail

# Functions for Google Cloud Service Account management
#
# This script is using gcloud instead of REST API calls to manage service accounts
# to avoid dealing with OAuth tokens and scopes. 
# If the command `gcloud auth print-access-token` could be translated into an API call,
# the script could be refactored to avoid the dependency on gcloud CLI.

LABEL_ORG="obs"
LABEL_DIVISION="engineering"
LABEL_TEAM="eng-productivity"
LABEL_EPHEMERAL="true"

function check_if_gcloud_installed() {
  if ! command -v gcloud &> /dev/null; then
    echo ":bk-status-failed: gcloud could not be found. Please install the Google Cloud SDK to use this plugin with service accounts."
    exit 1
  fi
}

# Create the service account
# Arguments:
#   $1: Service account name
#   $2: Project ID
#   $3: Repository name
#   $4: Hash
function create_service_account() {
  local -r SA_NAME="$1"
  local -r PROJECT_ID="$2"
  local -r REPOSITORY_NAME="$3"
  local -r HASH="$4"

  gcloud iam service-accounts create "$SA_NAME" \
    --description="Service account created by Buildkite GCP Auth Plugin for ${REPOSITORY_NAME}.\n Labels:\n org=${LABEL_ORG}\n division=${LABEL_DIVISION}\n team=${LABEL_TEAM}\n project=${REPOSITORY_NAME}\n ephemeral=${LABEL_EPHEMERAL}" \
    --display-name="Buildkite Plugin Ephemeral Service Account ${HASH}" \
    --project="$PROJECT_ID"

}

# Set the IAM policy to the service account
# Arguments:
#   $1: Service account email
#   $2: Project ID
function set_iam_policy() {
  local -r SA_ACCOUNT="$1"
  local -r PROJECT_ID="$2"
  local -r REQUEST_FILE="$3"

  gcloud projects add-iam-policy-binding "$PROJECT_ID" \
  --member="serviceAccount:$SA_ACCOUNT" \
  --role="roles/writer"

}

# Create and download the service account key
# Arguments:
#   $1: Service account email
#   $2: Project ID
#   $3: Service account key file path
function create_service_account_key() {
  local -r SA_ACCOUNT="$1"
  local -r PROJECT_ID="$2"
  local -r SA_KEY_FILE="$3"

  gcloud iam service-accounts keys create "$SA_KEY_FILE" \
    --iam-account="$SA_ACCOUNT" \
    --project="$PROJECT_ID"
}