#!/usr/bin/env bash

function send_message() {
  local -r SLACK_CHANNEL="$1"
  local -r MESSAGE="$2"
  cat <<- YAML | buildkite-agent pipeline upload
steps:
  - label: "Notify slack"
    command: echo "Notifying slack"
    notify:
      - slack:
          channels:
            - "$SLACK_CHANNEL"
          message: "$MESSAGE"
YAML
}